void throw_exception(const char* _msg)
{
    throw _msg;
}